services:
  chat-server:
    build: ./ServerApp
    environment:
      - CHAT_ROLE=Server
      - CHAT_USERNAME=prod-server
      - CHAT_PASSWORD=prod-pass
      - CHAT_PORT=9000
    ports:
      - "9000:9000"        # container-specific (structural)

  chat-client:
    build: ./ClientApp
    environment:
      - CHAT_ROLE=Client
      - CHAT_TARGETADDRESS=chat-server
      - CHAT_USERNAME=prod-client
      - CHAT_PASSWORD=prod-pass